### ISSUE TITLE
v0.1.0-alpha [checklist]

### ISSUE THREAD

**Issue by CharlesLiu-TOPNetwork** [telosprotocol/top-auto-upgrader#1]
Reminder...

- [x] support local build rs.
- [x] fetch from github release at `top-au-install.sh` `build_or_fetch_top_auto_upgrader`

- [x] transfer repos to telesprotocol
    - [x] `top-au-install.sh` : `daemon_script_url` 、`main echo Github repo address`
    - [x] `ReadMe.md` : `wget install script repo address`
